"""
train.py  —  LongTripOpt Model Training Pipeline
=================================================
Trains TWO models on the Urban Black dataset:

  1. FarePredictionModel   — Predicts `offered_fare` (regression)
  2. WTAModel              — Predicts `rider_acceptance_flag` (classification)
                             (Will-Take-Action: will the rider accept the fare?)

Strategy
--------
  • Load 50K synthetic dataset  (generated by generate_dataset.py)
  • Load real rides CSV          (data/rides_dataset_clean.csv)
  • Augment real data 50×        (oversampling to give it weight)
  • Feature-engineer both datasets with identical pipeline
  • Train/val split (80/20 on synthetic, hold out ALL real rows for final test)
  • Save models to models/  with joblib

Usage
-----
    python src/train.py
    python src/train.py --synthetic-data data/synthetic_rides_dataset_50k.csv \
                        --real-data data/rides_dataset_clean.csv \
                        --models-dir models/
"""
from __future__ import annotations

import argparse
import json
import math
import warnings
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import (
    HistGradientBoostingClassifier,
    HistGradientBoostingRegressor,
)
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
    roc_auc_score,
    precision_score,
    recall_score,
    f1_score,
    accuracy_score,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

try:
    import joblib
    HAS_JOBLIB = True
except ImportError:
    import pickle
    HAS_JOBLIB = False

warnings.filterwarnings("ignore")

# ─── paths ───────────────────────────────────────────────────────────────────
ROOT        = Path(__file__).resolve().parent.parent
SYNTH_DATA  = ROOT / "data" / "synthetic_rides_dataset_50k.csv"
REAL_DATA   = ROOT / "data" / "rides_dataset_clean.csv"
MODELS_DIR  = ROOT / "models"

# ─── fare slab constants (must match fare_calculator.py) ─────────────────────
BASE_KM     = 1.5
RATE_SHORT  = 25.0   # < 15 km
RATE_LT1    = 23.0   # 15–18 km
RATE_LT2    = 22.0   # 18–20 km
RATE_LT3    = 20.0   # ≥ 20 km
GST         = 0.05

TRIP_TYPE_ORDER = ["standard", "standard_long", "outskirts", "airport", "intercity"]
FUEL_ORDER      = ["LOW", "QUARTER", "HALF", "THREE_QUARTER", "FULL"]
COND_ORDER      = ["NEEDS_ATTENTION", "FAIR", "GOOD", "EXCELLENT"]
DEPOT_ZONES     = ["West-Pune", "Hinjewadi", "East-Pune", "North-Pune",
                   "Airport-Zone", "Central-Pune"]

# ─── feature sets ─────────────────────────────────────────────────────────────
FARE_FEATURES = [
    "actual_distance_km", "estimated_distance_km", "distance_error_ratio",
    "actual_duration_min", "estimated_duration_min", "approach_km",
    "speed_kmh",
    "trip_type_enc", "vehicle_type_enc",
    "is_airport", "is_intercity", "is_long_trip", "is_premium",
    "hour_of_day", "day_of_week", "is_peak_hour", "is_weekend", "is_night",
    "hour_sin", "hour_cos", "dow_sin", "dow_cos",
    "fare_slab_stage_id",
    "driver_daily_ride_km", "driver_overuse_km", "driver_shift_hours_elapsed",
]

WTA_FEATURES = [
    "actual_distance_km", "approach_km",
    "trip_type_enc", "vehicle_type_enc",
    "is_airport", "is_intercity", "is_long_trip", "is_premium",
    "hour_of_day", "day_of_week", "is_peak_hour", "is_weekend", "is_night",
    "hour_sin", "hour_cos", "dow_sin", "dow_cos",
    "driver_rating", "driver_total_trips",
    "driver_daily_ride_km", "driver_daily_dead_km",
    "driver_quota_km", "driver_overuse_km",
    "driver_shift_hours_elapsed", "driver_online_minutes",
    "driver_fuel_level_enc", "driver_vehicle_cond_enc",
    "shift_fatigue_score", "utilization_ratio",
    "low_fuel_flag", "poor_vehicle_flag", "end_of_shift_flag",
]
# ─────────────────────────────────────────────────────────────────────────────


def _fare_slab(km: float) -> int:
    """Return slab id 1–4 matching fare_calculator.py logic."""
    if km < 15:   return 1
    if km < 18:   return 2
    if km < 20:   return 3
    return 4


def _theoretical_fare(km: float, is_premium: bool, is_night: bool,
                      wait_min: float = 0.0, surge: float = 1.0) -> float:
    """Rule-based fare for sanity-check / label smoothing (matches calculator)."""
    inc_km  = max(0.0, km - BASE_KM)
    rate    = RATE_SHORT if km < 15 else (RATE_LT1 if km < 18 else (RATE_LT2 if km < 20 else RATE_LT3))
    dist    = (55.0 + inc_km * rate) * (1.10 if is_premium else 1.0)
    wait_ch = max(0.0, wait_min - 5.0) * 2.0
    night   = dist * 0.25 if is_night else 0.0
    weather = dist * max(0.0, surge - 1.0)
    sub     = dist + wait_ch + night + weather
    return round(sub * (1 + GST), 2)


def _encode_ordinal(series: pd.Series, order: list[str]) -> pd.Series:
    mapping = {v: i for i, v in enumerate(order)}
    return series.map(mapping).fillna(0).astype(int)


def feature_engineer(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    # ── distance / speed features ─────────────────────────────────────────
    df["actual_distance_km"]     = pd.to_numeric(df["actual_distance_km"],    errors="coerce").fillna(0)
    df["estimated_distance_km"]  = pd.to_numeric(df["estimated_distance_km"], errors="coerce").fillna(df["actual_distance_km"])
    df["approach_km"]            = pd.to_numeric(df.get("approach_km", pd.Series([2.0]*len(df))), errors="coerce").fillna(2.0)
    df["actual_duration_min"]    = pd.to_numeric(df.get("actual_duration_min", pd.Series([30]*len(df))), errors="coerce").fillna(30)
    df["estimated_duration_min"] = pd.to_numeric(df.get("estimated_duration_min", pd.Series([30]*len(df))), errors="coerce").fillna(df["actual_duration_min"])

    df["distance_error_ratio"] = (
        (df["estimated_distance_km"] - df["actual_distance_km"]) /
        df["actual_distance_km"].clip(lower=0.1)
    ).clip(-0.5, 0.5)

    df["speed_kmh"] = (
        df["actual_distance_km"] / (df["actual_duration_min"].clip(lower=1) / 60)
    ).clip(0, 120)

    # ── trip classification ───────────────────────────────────────────────
    tt = df["trip_type"].str.lower().str.strip()
    df["trip_type_enc"]  = _encode_ordinal(tt, TRIP_TYPE_ORDER)
    df["is_airport"]     = (tt == "airport").astype(int)
    df["is_intercity"]   = (tt == "intercity").astype(int)
    df["is_long_trip"]   = (tt.isin(["standard_long", "airport", "intercity", "outskirts"])).astype(int)

    vt = df["vehicle_type"].str.lower().str.strip()
    df["vehicle_type_enc"] = (vt == "premium").astype(int)
    df["is_premium"]        = df["vehicle_type_enc"]

    # ── time features ─────────────────────────────────────────────────────
    df["hour_of_day"] = pd.to_numeric(df.get("hour_of_day", pd.Series([12]*len(df))), errors="coerce").fillna(12).astype(int)
    df["day_of_week"] = pd.to_numeric(df.get("day_of_week", pd.Series([1]*len(df))),  errors="coerce").fillna(1).astype(int)
    df["is_peak_hour"]= df.get("is_peak_hour", pd.Series([False]*len(df))).map({True:1,False:0,"True":1,"False":0}).fillna(0).astype(int)
    df["is_weekend"]  = df.get("is_weekend", pd.Series([False]*len(df))).map({True:1,False:0,"True":1,"False":0}).fillna(0).astype(int)
    df["is_night"]    = ((df["hour_of_day"] >= 22) | (df["hour_of_day"] < 6)).astype(int)

    hr = df["hour_of_day"] * 2 * math.pi / 24
    dow= df["day_of_week"] * 2 * math.pi / 7
    df["hour_sin"] = np.sin(hr)
    df["hour_cos"] = np.cos(hr)
    df["dow_sin"]  = np.sin(dow)
    df["dow_cos"]  = np.cos(dow)

    # ── fare slab ─────────────────────────────────────────────────────────
    if "fare_slab_stage_id" not in df.columns:
        df["fare_slab_stage_id"] = df["actual_distance_km"].apply(_fare_slab)
    else:
        df["fare_slab_stage_id"] = pd.to_numeric(df["fare_slab_stage_id"], errors="coerce").fillna(1).astype(int)

    # ── driver features ───────────────────────────────────────────────────
    for col in ["driver_rating", "driver_total_trips", "driver_daily_ride_km",
                "driver_daily_dead_km", "driver_quota_km", "driver_overuse_km",
                "driver_shift_hours_elapsed", "driver_online_minutes"]:
        df[col] = pd.to_numeric(df.get(col, pd.Series([0.0]*len(df))), errors="coerce").fillna(0.0)

    df["driver_fuel_level_enc"] = _encode_ordinal(
        df.get("driver_fuel_level_start", pd.Series(["HALF"]*len(df))), FUEL_ORDER)
    df["driver_vehicle_cond_enc"] = _encode_ordinal(
        df.get("driver_vehicle_condition", pd.Series(["GOOD"]*len(df))), COND_ORDER)

    df["shift_fatigue_score"] = df["driver_shift_hours_elapsed"] / 12.0
    df["utilization_ratio"]   = df["driver_daily_ride_km"] / df["driver_quota_km"].clip(lower=1)
    df["low_fuel_flag"]       = (df["driver_fuel_level_enc"] <= 1).astype(int)
    df["poor_vehicle_flag"]   = (df["driver_vehicle_cond_enc"] == 0).astype(int)
    df["end_of_shift_flag"]   = (df["driver_shift_hours_elapsed"] >= 10.0).astype(int)

    # ── target: WTA ────────────────────────────────────────────────────────
    if "rider_acceptance_flag" in df.columns:
        df["wta_label"] = df["rider_acceptance_flag"].map(
            {True: 1, False: 0, "True": 1, "False": 0, 1: 1, 0: 0}
        ).fillna(0).astype(int)

    return df


def load_and_merge(synth_path: Path, real_path: Path,
                   real_oversample: int = 50) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Load synthetic + real data, return (train_df, test_real_df)."""
    print(f"Loading synthetic data from {synth_path} …")
    if synth_path.suffix.lower() == ".xlsx":
        df_synth = pd.read_excel(synth_path)
    else:
        df_synth = pd.read_csv(synth_path)
    print(f"  {len(df_synth):,} synthetic rows loaded")

    print(f"Loading real data from {real_path} …")
    if real_path.suffix.lower() == ".xlsx":
        df_real = pd.read_excel(real_path)
    else:
        df_real = pd.read_csv(real_path)
    print(f"  {len(df_real):,} real rows loaded")

    # Hold out 20% of real data for final test
    if len(df_real) > 10:
        real_train_df, real_test_df = train_test_split(df_real, test_size=0.20, random_state=42)
    else:
        real_train_df = df_real.copy()
        real_test_df  = df_real.copy()

    # Oversample training portion of real data
    real_aug = pd.concat([real_train_df] * real_oversample, ignore_index=True)
    print(f"  Augmented real (×{real_oversample}): {len(real_aug):,} rows for training")

    train_df = pd.concat([df_synth, real_aug], ignore_index=True)
    print(f"  Combined training set: {len(train_df):,} rows")
    return train_df, real_test_df


def train_fare_model(
    train_df: pd.DataFrame,
    test_df: pd.DataFrame,
) -> tuple:
    """Train a fare regression model. Returns (model, metrics_dict)."""
    print("\n── Fare Prediction Model ──────────────────────────────────────")
    target_col = "offered_fare"

    # Filter to rows with valid target
    train_df = train_df[pd.to_numeric(train_df[target_col], errors="coerce").notna()].copy()
    train_df[target_col] = pd.to_numeric(train_df[target_col])

    X = train_df[[c for c in FARE_FEATURES if c in train_df.columns]].fillna(0)
    y = train_df[target_col]

    X_tr, X_val, y_tr, y_val = train_test_split(X, y, test_size=0.10, random_state=42)
    print(f"  Train: {len(X_tr):,}  Val: {len(X_val):,}")

    model = HistGradientBoostingRegressor(
        max_iter=500,
        learning_rate=0.05,
        max_depth=7,
        min_samples_leaf=20,
        l2_regularization=0.1,
        random_state=42,
    )
    model.fit(X_tr, y_tr)

    preds_val = model.predict(X_val)
    mae  = mean_absolute_error(y_val, preds_val)
    rmse = math.sqrt(mean_squared_error(y_val, preds_val))
    r2   = r2_score(y_val, preds_val)
    mape = float(np.mean(np.abs((y_val - preds_val) / np.clip(y_val, 1, None))) * 100)
    print(f"  Val  MAE={mae:.2f}  RMSE={rmse:.2f}  R²={r2:.4f}  MAPE={mape:.2f}%")

    # Eval on real held-out test
    feat_cols = [c for c in FARE_FEATURES if c in test_df.columns]
    test_valid = test_df[pd.to_numeric(test_df.get(target_col, pd.Series()), errors="coerce").notna()].copy()
    if len(test_valid) > 0:
        test_valid[target_col] = pd.to_numeric(test_valid[target_col])
        X_te = test_valid[feat_cols].fillna(0)
        y_te = test_valid[target_col]
        preds_te = model.predict(X_te)
        mae_r  = mean_absolute_error(y_te, preds_te)
        rmse_r = math.sqrt(mean_squared_error(y_te, preds_te))
        r2_r   = r2_score(y_te, preds_te)
        mape_r = float(np.mean(np.abs((y_te - preds_te) / np.clip(y_te, 1, None))) * 100)
        print(f"  Real MAE={mae_r:.2f}  RMSE={rmse_r:.2f}  R²={r2_r:.4f}  MAPE={mape_r:.2f}%")
    else:
        mae_r = rmse_r = r2_r = mape_r = None

    metrics = {
        "val_mae": round(mae, 2), "val_rmse": round(rmse, 2),
        "val_r2": round(r2, 4),   "val_mape_pct": round(mape, 2),
        "real_mae": round(mae_r, 2) if mae_r else None,
        "real_rmse": round(rmse_r, 2) if rmse_r else None,
        "real_r2":   round(r2_r, 4)  if r2_r else None,
        "real_mape_pct": round(mape_r, 2) if mape_r else None,
    }
    return model, metrics, [c for c in FARE_FEATURES if c in train_df.columns]


def train_wta_model(
    train_df: pd.DataFrame,
    test_df: pd.DataFrame,
) -> tuple:
    """Train a rider acceptance (WTA) classification model."""
    print("\n── WTA (Rider Acceptance) Model ───────────────────────────────")

    if "wta_label" not in train_df.columns:
        print("  ⚠  wta_label missing — skipping WTA model")
        return None, {}, []

    feat_cols = [c for c in WTA_FEATURES if c in train_df.columns]
    X = train_df[feat_cols].fillna(0)
    y = train_df["wta_label"]

    X_tr, X_val, y_tr, y_val = train_test_split(X, y, test_size=0.10, random_state=42)
    print(f"  Train: {len(X_tr):,}  Val: {len(X_val):,}  Pos rate: {y_tr.mean():.2%}")

    model = HistGradientBoostingClassifier(
        max_iter=400,
        learning_rate=0.05,
        max_depth=6,
        min_samples_leaf=30,
        l2_regularization=0.1,
        random_state=42,
    )
    model.fit(X_tr, y_tr)

    preds_val = model.predict(X_val)
    proba_val = model.predict_proba(X_val)[:, 1]
    auc   = roc_auc_score(y_val, proba_val)
    prec  = precision_score(y_val, preds_val, zero_division=0)
    rec   = recall_score(y_val, preds_val, zero_division=0)
    f1    = f1_score(y_val, preds_val, zero_division=0)
    acc   = accuracy_score(y_val, preds_val)
    print(f"  Val  AUC={auc:.4f}  Prec={prec:.3f}  Rec={rec:.3f}  F1={f1:.3f}  Acc={acc:.3f}")

    metrics = {
        "val_auc_roc": round(auc, 4),
        "val_precision": round(prec, 3),
        "val_recall": round(rec, 3),
        "val_f1": round(f1, 3),
        "val_accuracy": round(acc, 3),
    }
    return model, metrics, feat_cols


def save_model(model, path: Path, name: str):
    if HAS_JOBLIB:
        import joblib
        joblib.dump(model, path)
    else:
        import pickle
        with open(path, "wb") as f:
            pickle.dump(model, f)
    print(f"  Saved {name} to {path}")


def main(args):
    synth_path  = Path(args.synthetic_data)
    real_path   = Path(args.real_data)
    models_dir  = Path(args.models_dir)
    models_dir.mkdir(parents=True, exist_ok=True)

    # ── Load & merge ────────────────────────────────────────────────────────
    train_raw, test_raw = load_and_merge(synth_path, real_path,
                                         real_oversample=args.real_oversample)

    # ── Feature engineering ─────────────────────────────────────────────────
    print("\nEngineering features …")
    train_fe = feature_engineer(train_raw)
    test_fe  = feature_engineer(test_raw)
    print(f"  Features ready: {len(train_fe.columns)} columns in train set")

    # ── Fare model ──────────────────────────────────────────────────────────
    fare_model, fare_metrics, fare_feats = train_fare_model(train_fe, test_fe)
    fare_path = models_dir / "fare_model.pkl"
    save_model(fare_model, fare_path, "fare_model")

    # ── WTA model ───────────────────────────────────────────────────────────
    wta_model, wta_metrics, wta_feats = train_wta_model(train_fe, test_fe)
    if wta_model is not None:
        wta_path = models_dir / "wta_model.pkl"
        save_model(wta_model, wta_path, "wta_model")

    # ── Save feature list ────────────────────────────────────────────────────
    feature_meta = {"fare_features": fare_feats, "wta_features": wta_feats}
    feat_path = models_dir / "feature_columns.json"
    with open(feat_path, "w", encoding="utf-8") as f:
        json.dump(feature_meta, f, indent=2)
    print(f"  Feature metadata saved to {feat_path}")

    # ── Update model metadata ────────────────────────────────────────────────
    meta = {
        "trained_at":  datetime.now().isoformat(),
        "framework":   "sklearn.HistGradientBoosting (LightGBM-compatible)",
        "strategy":    f"{len(train_raw):,} rows ({synth_path.name} + real ×{args.real_oversample})"
                       f" → {len(test_raw)} real held-out test",
        "fare_rules": {
            "base_fare_rs":    55,
            "base_km":         1.5,
            "rate_short_per_km":  25,
            "rate_long_t1_per_km": 23,
            "rate_long_t2_per_km": 22,
            "rate_long_t3_per_km": 20,
            "long_t1_km_range": "15–<18",
            "long_t2_km_range": "18–<20",
            "long_t3_km_range": "≥20",
            "wait_free_min":    5,
            "wait_rate_per_min": 2,
            "night_surcharge_pct": 25,
            "weather_surge_pct_range": "10–20",
            "gst_pct":          5,
        },
        "shift_constraints": {
            "min_rides_per_shift": 25,
            "shift_hours":         12,
            "min_km_per_shift":    135,
        },
        "n_synthetic":  len(pd.read_excel(synth_path) if synth_path.suffix.lower() == ".xlsx" else pd.read_csv(synth_path)) if synth_path.exists() else None,
        "n_real_train": len(test_raw),
        "fare_metrics":  fare_metrics,
        "wta_metrics":   wta_metrics,
        "fare_features": fare_feats,
        "wta_features":  wta_feats,
    }
    meta_path = models_dir / "model_metadata.json"
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2, ensure_ascii=False)
    print(f"\n  model_metadata.json saved to {meta_path}")
    print("\nTraining complete!")
    print(f"  Fare model  : {fare_path}")
    if wta_model:
        print(f"  WTA  model  : {wta_path}")
    print(f"  Metadata    : {meta_path}")


def parse_args():
    p = argparse.ArgumentParser(description="LongTripOpt Training Pipeline")
    p.add_argument("--synthetic-data", default=str(SYNTH_DATA))
    p.add_argument("--real-data",       default=str(REAL_DATA))
    p.add_argument("--models-dir",     default=str(MODELS_DIR))
    p.add_argument("--real-oversample", type=int, default=50,
                   help="How many times to duplicate real training rows (default 50)")
    return p.parse_args()


if __name__ == "__main__":
    main(parse_args())
